DROP DATABASE IF EXISTS mod_acc;
DROP DATABASE IF EXISTS mod_peo;
DROP DATABASE IF EXISTS mod_cur;
DROP DATABASE IF EXISTS mod_acc_peo;
DROP DATABASE IF EXISTS mod_peo_cur;

CREATE DATABASE mod_acc;
CREATE DATABASE mod_peo;
CREATE DATABASE mod_cur;
CREATE DATABASE mod_acc_peo;
CREATE DATABASE mod_peo_cur;
