#!/bin/bash
USERNAME="postgres"
PASSWORD="postgres"

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

PGPASSWORD=$PASSWORD psql -U $USERNAME -f $SCRIPTPATH/modules/CREATE_DATABASES.sql

PGPASSWORD=$PASSWORD psql -U $USERNAME mod_acc -f $SCRIPTPATH/modules/MODULE_ACCESS_CLEAN.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_acc -f $SCRIPTPATH/modules/MODULE_ACCESS_DDL.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_acc -f $SCRIPTPATH/modules/MODULE_ACCESS_FUNCTIONS.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_acc -f $SCRIPTPATH/modules/MODULE_ACCESS_DML.sql

PGPASSWORD=$PASSWORD psql -U $USERNAME mod_cur -f $SCRIPTPATH/modules/MODULE_CURRICULUM_CLEAN.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_cur -f $SCRIPTPATH/modules/MODULE_CURRICULUM_DDL.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_cur -f $SCRIPTPATH/modules/MODULE_CURRICULUM_FUNCTIONS.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_cur -f $SCRIPTPATH/modules/MODULE_CURRICULUM_DML.sql

PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f $SCRIPTPATH/modules/MODULE_PEOPLE_CLEAN.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f $SCRIPTPATH/modules/MODULE_PEOPLE_DDL.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f $SCRIPTPATH/modules/MODULE_PEOPLE_FUNCTIONS.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f $SCRIPTPATH/modules/MODULE_PEOPLE_DML.sql

PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f $SCRIPTPATH/modules/INTER_MOD_PEO_CUR_CLEAN.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f $SCRIPTPATH/modules/INTER_MOD_PEO_CUR_DDL.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f $SCRIPTPATH/modules/INTER_MOD_PEO_CUR_FUNCTIONS.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f $SCRIPTPATH/modules/INTER_MOD_PEO_CUR_DML.sql

PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f $SCRIPTPATH/modules/INTER_MOD_ACC_PEO_CLEAN.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f $SCRIPTPATH/modules/INTER_MOD_ACC_PEO_DDL.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f $SCRIPTPATH/modules/INTER_MOD_ACC_PEO_FUNCTIONS.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f $SCRIPTPATH/modules/INTER_MOD_ACC_PEO_DML.sql
