#!/bin/bash
USERNAME="postgres"
PASSWORD="postgres"

PGPASSWORD=$PASSWORD psql -U $USERNAME -f modules/CREATE_DATABASES.sql

PGPASSWORD=$PASSWORD psql -U $USERNAME mod_acc -f modules/MODULE_ACCESS_CLEAN.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_acc -f modules/MODULE_ACCESS_DDL.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_acc -f modules/MODULE_ACCESS_FUNCTIONS.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_acc -f modules/MODULE_ACCESS_DML.sql

PGPASSWORD=$PASSWORD psql -U $USERNAME mod_cur -f modules/MODULE_CURRICULUM_CLEAN.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_cur -f modules/MODULE_CURRICULUM_DDL.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_cur -f modules/MODULE_CURRICULUM_FUNCTIONS.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_cur -f modules/MODULE_CURRICULUM_DML.sql

PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f modules/MODULE_PEOPLE_CLEAN.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f modules/MODULE_PEOPLE_DDL.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f modules/MODULE_PEOPLE_FUNCTIONS.sql
PGPASSWORD=$PASSWORD psql -U $USERNAME mod_peo -f modules/MODULE_PEOPLE_DML.sql
