DROP FOREIGN TABLE IF EXISTS disciplina_foreign;
DROP FOREIGN TABLE IF EXISTS aluno_foreign;
DROP FOREIGN TABLE IF EXISTS professor_foreign;
DROP TABLE IF EXISTS cursa;
DROP TABLE IF EXISTS planeja;
DROP TABLE IF EXISTS oferecimento;
DROP TABLE IF EXISTS cursa_curriculo;
DROP SERVER IF EXISTS cur_server;
DROP SERVER IF EXISTS peo_server;