CREATE TABLE pessoa (
	cpf VARCHAR(11) PRIMARY KEY CHECK (char_length(cpf) = 11),
	nome VARCHAR(100)
);

CREATE TABLE aluno (
	nusp INTEGER PRIMARY KEY,
	cpf VARCHAR(11) REFERENCES pessoa(cpf) ON DELETE CASCADE ON UPDATE CASCADE,
	ano_ingresso INTEGER CHECK (ano_ingresso >= 1934)
);

CREATE TABLE professor (
	cpf VARCHAR(11) PRIMARY KEY REFERENCES pessoa(cpf) ON DELETE CASCADE ON UPDATE CASCADE,
	area_formacao VARCHAR(50)
);

CREATE TABLE administrador (
	cpf VARCHAR(11) PRIMARY KEY REFERENCES pessoa(cpf) ON DELETE CASCADE ON UPDATE CASCADE,
	inicio DATE,
	fim DATE
);
