CREATE EXTENSION IF NOT EXISTS pgcrypto;

SELECT cria_pessoa('Bortolli');
SELECT cria_pessoa('Teotonio');
SELECT cria_pessoa('Daher');
SELECT cria_pessoa('Jonas');
SELECT cria_pessoa('Enzo');
SELECT cria_pessoa('Moretto');
SELECT cria_pessoa('Rubens');
SELECT cria_pessoa('Thiago');
SELECT cria_pessoa('Ricardo');
SELECT cria_pessoa('Breno');
SELECT cria_pessoa('Jef');
SELECT cria_pessoa('Carlinhos');
SELECT cria_pessoa('Hirata');
SELECT cria_pessoa('Renata');
SELECT cria_pessoa('Daniel');
SELECT cria_pessoa('Fabio');
SELECT cria_pessoa('Coelho');
SELECT cria_pessoa('Cris');
SELECT cria_pessoa('Roberto');
SELECT cria_pessoa('Nina');
SELECT cria_pessoa('Decio');

SELECT cria_aluno('Bortolli', 2016);
SELECT cria_aluno('Teotonio', 2016);
SELECT cria_aluno('Daher', 2015);
SELECT cria_aluno('Jonas', 2016);
SELECT cria_aluno('Enzo', 2015);
SELECT cria_aluno('Moretto', 2017);
SELECT cria_aluno('Rubens', 2016);
SELECT cria_aluno('Thiago', 2017);
SELECT cria_aluno('Ricardo', 2015);
SELECT cria_aluno('Breno', 2017);

SELECT cria_professor('Jef', 'Banco de dados');
SELECT cria_professor('Carlinhos', 'Teoria');
SELECT cria_professor('Hirata', 'Machie Learning');
SELECT cria_professor('Renata', 'IA');
SELECT cria_professor('Daniel', 'Sistemas');
SELECT cria_professor('Fabio', 'Sistemas');
SELECT cria_professor('Coelho', 'Teoria');
SELECT cria_professor('Cris', 'Teoria');
SELECT cria_professor('Roberto', 'Machie Learning');
SELECT cria_professor('Nina', 'Machie Learning');

SELECT cria_administrador('Jef', '20-05-2019', '20-05-2020');
SELECT cria_administrador('Carlinhos', '01-01-2010', '01-01-2040');
SELECT cria_administrador('Hirata', '01-01-2015', '01-01-2050');
SELECT cria_administrador('Renata', '03-01-2016', '01-01-2050');
SELECT cria_administrador('Daniel', '20-05-2016', '20-01-2040');
SELECT cria_administrador('Fabio', '06-01-2017', '01-01-2050');
SELECT cria_administrador('Coelho', '07-01-2015', '01-01-2030');
SELECT cria_administrador('Cris', '07-05-2018', '01-01-2030');
SELECT cria_administrador('Nina', '01-05-2019', '01-01-2020');
SELECT cria_administrador('Decio', '02-01-2019', '01-01-2022');